export const FETCH_COUNTRIES_LIST_REQUEST = "FETCH_COUNTRIES_LIST_REQUEST";
export const FETCH_COUNTRIES_LIST_SUCCESS = "FETCH_COUNTRIES_LIST_SUCCESS";
export const FETCH_COUNTRIES_LIST_FAILURE = "FETCH_COUNTRIES_LIST_FAILURE";
